name: Optimum-rbln / Dispatch / PR

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR number to run"
        required: true
        type: string

jobs:
  optimum-rbln-pytest:
    uses: ./.github/workflows/rbln_optimum_pytest.yaml
    with:
      pr_number: ${{ inputs.pr_number }}
    secrets: inherit
  
  optimum-rbln-inference-test:
    uses: ./.github/workflows/rbln_optimum_inference_test.yaml
    with:
      pr_number: ${{ inputs.pr_number }}
    secrets: inherit
