name: Update uv.lock on Dependabot PR

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]

jobs:
  update-uv-lock:
    # Only run on dependabot PRs
    if: github.actor == 'dependabot[bot]'
    runs-on: Standard GitHub-hosted runners
    
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      
      - name: Check if pyproject.toml was modified
        id: check-pyproject
        run: |
          if git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | grep -q "pyproject.toml"; then
            echo "modified=true" >> $GITHUB_OUTPUT
          else
            echo "modified=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Update uv.lock
        if: steps.check-pyproject.outputs.modified == 'true'
        run: |
          # Update uv.lock based on pyproject.toml changes
          uv lock --upgrade
      
      - name: Check for changes in uv.lock
        id: check-changes
        if: steps.check-pyproject.outputs.modified == 'true'
        run: |
          if git diff --quiet uv.lock; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push changes
        if: steps.check-changes.outputs.changed == 'true'
        run: |
          git add uv.lock
          git commit -m "chore: update uv.lock after dependency changes"
          git push
      
      - name: Comment on PR
        if: steps.check-changes.outputs.changed == 'true'
        uses: actions/github-script@v7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🔒 **uv.lock updated**\n\nI\'ve automatically updated the `uv.lock` file to reflect the dependency changes in `pyproject.toml`.'
            })
      
      - name: Comment if no changes needed
        if: steps.check-changes.outputs.changed == 'false' && steps.check-pyproject.outputs.modified == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'ℹ️ **No uv.lock changes needed**\n\nThe dependency changes in `pyproject.toml` don\'t require updating `uv.lock`.'
            })
